[package]
name = "pacman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
crossterm = "0.27"
log = "0.4.20"
log4rs = "1.2.0"
tui = { package = "ratatui", version = "0.24" }
